include: [secrets.yaml]

directory: ~/Music
library: ~/.config/beets/library.db
import:
    move: yes
    copy: no
    write: yes

scrub:
    auto: yes

plugins: fetchart lyrics lastgenre scrub inline spotify embedart

embedart:
    auto: yes
    remove_art_file: yes

lyrics:
    auto: yes
    force: yes
    synced: yes
    keep_synced: yes
    sources: lrclib genius

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
