fork = true
frame = "none"
idle = true
maximized = true
no-multigrid = false
tabs = true
srgb = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = true

[font]
normal = "FantasqueSansM Nerd Font Mono"
size = 11.0

